aws-region                = "us-east-1"
instance-name             = "jump-eks-project-2"
key-name                  = "murali_personal_use1"
eks-jump-sg               = "eks-project-2-jump-sg"
eks-jump-instance-profile = "Admin-access"
